CREATE TABLE IF NOT EXISTS "GS_tblServer" (
	"nServerId" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	"sHostName" TEXT NOT NULL,
	"tsLastSeen" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "GS_tblProcess" (
	"nProcessId" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	"nServerId" INTEGER NOT NULL REFERENCES "GS_tblServer"("nServerId"),
	"tsLastSeen" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "GS_tblRoom" (
	"nRoomId" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	"nServerId" INTEGER NOT NULL REFERENCES "GS_tblServer"("nServerId"),
	"nRoomType" INTEGER NOT NULL,
	"nUniqueId" INTEGER NOT NULL,
	"binCreateData" BYTEA NOT NULL
);

CREATE UNIQUE INDEX "GS_tblRoom_nRoomType_nUniqueId" ON "GS_tblRoom"("nRoomType","nUniqueId") WHERE "nUniqueId" > 0;


CREATE TABLE IF NOT EXISTS "GS_tblUser" (
	"nUserId" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY
);