CREATE TABLE IF NOT EXISTS "GS_tblServer" (
	"nServerId" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	"sHostName" TEXT NOT NULL,
	"tsLastSeen" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "GS_tblRoom" (
	"nRoomId" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	"nServerId" INTEGER NOT NULL REFERENCES "GS_tblServer"("nServerId"),
	"sName" TEXT
);

CREATE TABLE IF NOT EXISTS "GS_tblUser" (
	"nUserId" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY
);